name: slr_env # 환경 이름 (원하는 대로 변경 가능)
channels:
  - defaults
  - conda-forge # 일부 패키지는 conda-forge 채널에 있을 수 있습니다.
dependencies:
  - python=3.10
  - pandas=2.1.4
  - numpy=1.26.2
  - scikit-learn=1.3.2
  - requests=2.31.0
  - beautifulsoup4=4.12.2
  - openpyxl # pandas가 Excel 파일 읽고 쓸 때 필요
  - matplotlib
  - seaborn
  # zotero-py는 pip로 설치하는 것이 일반적일 수 있습니다.
  # conda에 없다면 아래 pip 섹션으로 옮깁니다.
  # - zotero-py # 예: zotero-py=0.7.1 (conda search zotero-py로 버전 확인)
  - pip # pip 명령어를 conda 환경 내에서 사용하기 위해 필요
  - pip:
    - zotero-py # PyPI에서 zotero-py의 원하는 버전을 명시 (예시 버전)
    # - some_other_pip_package # pip으로 설치해야 하는 다른 패키지가 있다면 추가